from iqoptionapi.stable_api import IQ_Option
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd=True
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM=open
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdz=IOError
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN=print
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd=float
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzN=ValueError
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd=str
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz=False
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz=int
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM=round
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNzd=id
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNzM=list
import PySimpleGUI as sg
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzg=sg.WIN_CLOSED
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMgN=sg.Window
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMgz=sg.Column
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNM=sg.Checkbox
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNg=sg.Radio
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN=sg.Input
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMg=sg.Frame
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzgN=sg.Image
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzgM=sg.Button
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNM=sg.Output
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz=sg.Text
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgMN=sg.change_look_and_feel
import time
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN=time.sleep
import requests
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMNg=requests.get
import logging
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNgz=logging.DEBUG
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMNz=logging.disable
import configparser
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNgM=configparser.RawConfigParser
import json
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNzM=json.dumps
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNzg=json.loads
import os
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNMg=os.path
import sys
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdzM=sys.stdout
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNMz=sys.exit
import socket
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdMN=socket.SOCK_STREAM
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdMz=socket.AF_INET
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdzN=socket.socket
import os
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNMg=os.path
from datetime import datetime,date,timedelta
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzdM=date.today
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdNM=datetime.utcfromtimestamp
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdNz=datetime.strptime
from dateutil import tz
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzdN=tz.gettz
import threading
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd=threading.Thread
from colorama import init,Fore,Back
from random import randint
import pyrebase
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMN=pyrebase.initialize_app
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMNz(level=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNgz))
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgMN('Black')
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgzN=[[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('    ')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNM(size=(83,35),font=('Helvetica',11),key='-OUT-')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzgM('  SALVAR CONFIGURACOES ',key='salvar')]]
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgMz=[[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz(''),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzgN(r'log/log.png',size=(200,205))],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('       '),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzgM('  INICIAR OPERACOES  ',key='iniciar')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMg(' Acesso ',[[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('Email IQ: ',key='txtw'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN(size=(25,0),key='email',background_color='white',text_color='black')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('Senha IQ:'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN(size=(25,0),key='senha',background_color='white',text_color='black',password_char='*')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz(' '),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNg('Treinamento',key='treinamento',group_id='1',default='true'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('     '),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNg('Real',key='real',group_id='1'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('       ')],])],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMg(' Preco da Operacao ',[[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNM('em %',key='porcentagem_preco'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('Valor: '),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN(size=(12,0),key='preco',background_color='white',text_color='black'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('       ')],])],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMg(' Gerenciamento ',[[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNM('Filtro D.BOT',key='filtroDbot')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNg('Martingale',key='martingale',group_id='2'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNg('Soros',key='soros',group_id='2'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNg('SorosGale',key='sorosGale',group_id='2')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('Nivel:        '),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN(size=(17,0),key='nivel_Estrategia',background_color='white',text_color='black'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz(' ')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNM('Martingale PO',key='martingalePO')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('Nivel: '),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN(size=(5,0),key='nivel_Estrategia_PO',background_color='white',text_color='black'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('Fator Mg: '),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN(size=(5,0),key='fatorMG',background_color='white',text_color='black'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('X')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('Payout:    '),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN(size=(17,0),key='payout',background_color='white',text_color='black'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz(' ')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('Stop Win: '),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN(size=(17,0),key='stop_win',background_color='white',text_color='black'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz(' ')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgNz('Stop Loss:'),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzMN(size=(17,0),key='stop_loss',background_color='white',text_color='black')],[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdzNM('Stop em %',key='gerenciamento')],])],]
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgMN=[[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMgz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgMz),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMgz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgzN)]]
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMgN('D.BOT',icon='log/log.ico',finalize=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd).layout(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgMN)
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz.Finalize()
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['iniciar'].update(disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgN
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMg
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMg=[]
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMN
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMN=[]
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg=0
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM=0
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz=0
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN=0
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg=0
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN=0
global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg=0
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNMg.isfile('./setup.conf')
if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNz:
 try:
  file=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('setup.conf')
 except wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdz:
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('Ocorreu um erro, voce deve definir as configuracoes no Configurador primeiro. \n\n O sistema sera encerrado')
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN(5)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNgM()
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.read('setup.conf')
 try:
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgM
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('USER','email')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzg
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('USER','senha')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzM
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzM="""{"code":"invalid_credentials","message":"You entered the wrong credentials. Please check that the login/password is correct."}"""
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMg
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','tipo_conta').lower()
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','preco_operacao'))
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzM
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','porc_preco')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzN
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','filtroDbot')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMz
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','martingale')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMN
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','martingalePO')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNz
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','soros')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNM
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','sorosGale')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','nivel_Estrategia')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQN
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','nivel_Estrategia_PO')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','fatorMG')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMN
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','payout')
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('GERENCIAMENTO','take_profit'))
  if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=='0' or wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=='':
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=100000
  else:
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('GERENCIAMENTO','stop_loss')
  if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=='0' or wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=='':
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=100000
  else:
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM)
  global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQz
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('GERENCIAMENTO','porcentagem')
 except wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzN:
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\n\n    Inconsistencia nas configuracoes especificadas, \n    voce nao pode deixar campos em branco ou usar virgula em numero decimal!\n    Assista todos os videos de configuracao para nao ter nenhuma duvida!')
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['email'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgM)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['senha'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzg)
 if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMg=='t':
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['treinamento'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
 else:
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['real'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['preco'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['porcentagem_preco'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzM)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['stop_win'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('GERENCIAMENTO','take_profit'))
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['stop_loss'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('GERENCIAMENTO','stop_loss'))
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['gerenciamento'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQz)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['filtroDbot'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzN)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['martingale'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMz)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['martingalePO'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMN)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['soros'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNz)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['sorosGale'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNM)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['nivel_Estrategia'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['nivel_Estrategia_PO'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQN)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['fatorMG'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['payout'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMN)
def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzQg():
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('setup'+'.conf','w+',encoding='utf8')
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('[USER]')
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nemail='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['email'])
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nsenha='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['senha'])
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\n[TRADE]')
 if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['real']:
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzN='r'
 else:
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzN='t'
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\ntipo_conta='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzN)
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nporc_preco='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['porcentagem_preco']))
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\npreco_operacao='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['preco'])
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nfiltroDbot='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['filtroDbot']))
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nmartingale='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['martingale']))
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nmartingalePO='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['martingalePO']))
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nsoros='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['soros']))
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nsorosGale='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['sorosGale']))
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nnivel_Estrategia='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['nivel_Estrategia'])
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nnivel_Estrategia_PO='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['nivel_Estrategia_PO'])
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nfatorMG='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['fatorMG'])
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\npayout='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['payout'])
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\n[GERENCIAMENTO]')
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nporcentagem='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['gerenciamento']))
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\ntake_profit='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['stop_win'])
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.writelines('\nstop_loss='+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ['stop_loss'])
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQN.close()
while wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
 wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMzQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz.read()
 if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMNQ in(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzg,'Exit'):
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz.close()
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNMz()
  break
 if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMNQ=='salvar':
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['iniciar'].update(disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzQg()
 if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMNQ=='iniciar':
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['iniciar'].update(disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['salvar'].update(disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzQM(msg='    Por favor, verifique as configuracoes de TRADE'):
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN(msg)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\n    Reinicie o sistema para tentar novamente... \n ')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNMz()
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzgQ(x,retorno=1):
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMNz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdNz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdNM(x).strftime('%Y-%m-%d %H:%M:%S'),'%Y-%m-%d %H:%M:%S')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMNz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMNz.replace(tzinfo=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzdN('GMT'))
   return wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMNz.astimezone(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzdN('America/Sao Paulo')))[:-6]if retorno==1 else wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMNz.astimezone(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzdN('America/Sao Paulo'))
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzgM(x,y):
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNQz=timedelta(milliseconds=x)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNQM=timedelta(milliseconds=y)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNzQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNQz.seconds
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNzM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNQM.seconds
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNMQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNzM-wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNzQ
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNMz=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNMQ%3600)//60
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNMz==0:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNMz=1
   return wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgNMz
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzMQ():
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzgQ
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQMg
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
   while wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
    for wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQgN in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzgQ:
     a=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdzN(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdMz,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdMN)
     a.settimeout(.5)
     try:
      b=a.connect_ex((wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQgN,80))
      if b==0:
       if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQgM==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz:
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQMg=db.child("sinais/1").stream(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMgQ)
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> CONECTADO AO BANCO DE DADOS COM SUCESSO!\n')
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
     except:
      pass
      if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQgM==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQMg.close()
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\nPERDA DE CONEXAO COM O BANCO DE DADOS, VERIFIQUE SUA INTERNET OU UM POSSIVEL BLOQUEIO DO ANTIVIRUS')
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> TENTANDO RECONECTAR...\n')
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
     a.close()
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzMg():
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQMN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
   while wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
    if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.check_connect()==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz:
     if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQMN==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\nPERDA DE CONEXAO COM A IQ OPTION, VERIFIQUE SUA INTERNET OU UM POSSIVEL BLOQUEIO DO ANTIVIRUS')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> TENTANDO RECONECTAR...\n')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQMN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.connect()
    else:
     if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQMN==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz:
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> CONECTADO A IQ OPTION COM SUCESSO!\n')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQMN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg():
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNzg(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNzM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.get_profile_ansyc()))
   return wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg):
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> MARTINGALE:\n')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQNg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN*wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ)
    if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMN:
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd(target=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgzN,args=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQNg,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg),daemon=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd).start()
    elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMg:
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd(target=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgzM,args=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQNg,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg),daemon=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd).start()
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n---> MARTINGALE:\n')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMgQ(message):
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQN
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMQ
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(message["data"])
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMQ!=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQN:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQN
    if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM:
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQN.split(';')
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMN[0]
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMN[1]
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMN[2])
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMN[3]
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMN[4]
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
     global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg=0
     if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzN==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz:
      if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMN:
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd(target=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgzN,args=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg),daemon=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd).start()
      elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMg:
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd(target=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgzM,args=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg),daemon=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd).start()
     if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzN==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd and wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgQ=='t':
      if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMN:
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd(target=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgzN,args=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg),daemon=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd).start()
      elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMg:
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd(target=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgzM,args=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg),daemon=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd).start()
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMgz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg,tipo,timeframe=1):
   if tipo=='turbo':
    a=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.get_all_profit()
    return wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(100*a[wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg]['turbo'])
   elif tipo=='digital':
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.subscribe_strike_list(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg,timeframe)
    while wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
     d=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.get_digital_current_profit(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg,timeframe)
     if d!=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz:
      d=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(d)
      break
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN(1)
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.unsubscribe_strike_list(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg,timeframe)
    return d
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMzQ():
   while wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
    global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMg
    global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMN
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.get_all_open_time()
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMg.clear()
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMN.clear()
    for wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQg in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg['digital']:
     if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg['digital'][wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQg]['open']==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMgz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQg,'digital')
      if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQM>=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMN):
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMg.append(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQg)
     continue
    for wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQg in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg['turbo']:
     if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNg['turbo'][wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQg]['open']==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMgz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQg,'turbo')
      if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQM>=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMN):
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzMN.append(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNQg)
     continue
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN(1200)
    continue
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMzg(res):
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM
   if res=='win':
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> STOP WIN - FOI UM PRAZER BATER META PARA VOCE :)')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n---> ---> STOP WIN :)')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
   elif res=='loss':
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> STOP LOSS - DESCULPE, HOJE NAO FOI MEU DIA :(')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n---> STOP LOSS :(')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgzM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg):
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNzd=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.buy_digital_spot(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM.lower(),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg)
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgQ:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> OPERACAO:')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('       ATIVO:',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,'| DIRECAO:',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,'| EXPIRACAO:',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg,'M','| VALOR:',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg()['currency_char'],wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,2))
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n---> OPERACAO:')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n     ATIVO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ)+'| DIRECAO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM)+'| EXPIRACAO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg)+'M'+'| VALOR:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz['currency_char'])+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,3)))
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
    while wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.check_win_digital_v2(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNzd)
     if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgQ:
      if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM>0:
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ+=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('       RESULTADO: WIN    |','LUCRO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg()['currency_char'])+' ',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2),' :)')
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n     RESULTADO: WIN    |'+'LUCRO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz['currency_char'])+' '+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)+' :)')
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgMz()
       if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNM:
        if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg==0:
         if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM):
          wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
          wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz=0
          wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg=0
         elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz<wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM):
          wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2)
          wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz+=1
        else:
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2)
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN,2)
        if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg!=0 and wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN>=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN:
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('    SOROSGALE VOLTANDO AO NIVEL 0')
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg=0
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN=0
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN=0
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz=0
       elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNz:
        global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM
        if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM)>wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM:
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\n---> SOROS:\n')
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2)
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM+=1
        else:
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM=0
      else:
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz+=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('       RESULTADO: LOSS    |','PREJUIZO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg()['currency_char'])+' ',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2),' :(')
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n     RESULTADO: LOSS   |'+'PREJUIZO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz['currency_char'])+' '+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)+' :(')
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM=0
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgMz()
       if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMz:
        if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM)>wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg:
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg+=1
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg)
        else:
         if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMN:
          if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQN)>wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg:
           wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> MARTINGALE PROXIMA OPERACAO:\n')
           wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg+=1
           wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN*wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ)
       elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNM:
        if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg==0:
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ/2
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg+=1
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
        else:
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN=0
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN+=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN/2
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN/2
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg+=1
       elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMN:
        if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQN)>wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg:
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> MARTINGALE PROXIMA OPERACAO:\n')
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg+=1
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN*wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ)
      break
   else:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('    A QUERIDA IQ BLOQUEOU MINHA ENTRADA :(')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('-'*131)
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgzN(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg):
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg
   while wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNzd=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.buy(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM.lower(),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg)
    if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgQ:
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN(randint(0,4))
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> OPERACAO:')
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('       ATIVO:',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,'| DIRECAO:',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,'| EXPIRACAO:',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg,'M','| VALOR:',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg()['currency_char'],wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,3))
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n---> OPERACAO:')
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n     ATIVO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ)+'| DIRECAO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM)+'| EXPIRACAO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg)+'M'+'| VALOR:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz['currency_char'])+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,3)))
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.check_win_v3(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNzd),3)
     if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM>0:
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ+=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('       RESULTADO: WIN    |','LUCRO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg()['currency_char'])+' ',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2),' :)')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n     RESULTADO: WIN    |'+'LUCRO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz['currency_char'])+' '+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)+' :)')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgMz()
      if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNM:
       if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg==0:
        if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM):
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz=0
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg=0
        elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz<wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM):
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2)
         wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz+=1
       else:
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2)
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN,2)
       if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg!=0 and wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN>=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN:
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('    SOROSGALE VOLTANDO AO NIVEL 0')
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg=0
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN=0
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN=0
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgz=0
      elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNz:
       global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM
       if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM)>wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM:
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> SOROS:\n')
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n---> SOROS:\n')
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2)
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM+=1
       else:
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM=0
      break
     elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM==0:
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('      RESULTADO: DOJI    |','LUCRO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg()['currency_char'])+' '+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)+' :|')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n     RESULTADO: DOJI    |'+'LUCRO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz['currency_char'])+' '+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)+' :|')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgMz()
      break
     else:
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz+=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('       RESULTADO: LOSS    |','PREJUIZO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg()['currency_char'])+' ',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,2),' :(')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n     RESULTADO: LOSS   |'+'PREJUIZO:'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz['currency_char'])+' '+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM)+' :(')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNM=0
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgMz()
      if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMz:
       if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM)>wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg:
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzNg+=1
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNQ,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNgM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgNM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMQg)
       else:
        if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMN:
         if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQN)>wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg:
          wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> MARTINGALE PROXIMA OPERACAO:\n')
          wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg+=1
          wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN*wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ)
      elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNM:
       if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg==0:
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ/2
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg+=1
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
       else:
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzN=0
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN+=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN/2
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMgN/2
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMzg+=1
      elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMN:
       if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQN)>wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg:
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('---> MARTINGALE PROXIMA OPERACAO:\n')
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQMNg+=1
        wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMgN*wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ)
      break
   else:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('    A QUERIDA IQ BLOQUEOU MINHA ENTRADA :(')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('-'*131)
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
  def wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdgMz():
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ)-(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz)*-1)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN(' ')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('       LUCRO PARCIAL: {} | PERDA PARCIAL: {} | TOTAL: {}'.format(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ,2),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz,2),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN,2)))
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('-'*131)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('Log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','a',encoding='utf8')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n       LUCRO PARCIAL: {} | PERDA PARCIAL: {} | TOTAL: {}'.format(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ,2),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz,2),wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNdM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN,2)))
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('-'*100)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.write('\n')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN>=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQM:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMzg('win')
   elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN<=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgzQ:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMzg('loss')
  try:
   file=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('setup.conf')
  except wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdz:
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('Ocorreu um erro, voce deve definir as configuracoes no Configurador primeiro. \n\n O sistema sera encerrado')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN(5)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNMz()
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNgM()
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.read('setup.conf')
  try:
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('USER','email')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('USER','senha')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzM="""{"code":"invalid_credentials","message":"You entered the wrong credentials. Please check that the login/password is correct."}"""
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','tipo_conta').lower()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','preco_operacao'))
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','porc_preco')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','filtroDbot')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','martingale')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','martingalePO')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','soros')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('TRADE','sorosGale')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','nivel_Estrategia')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','nivel_Estrategia_PO')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','fatorMG')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('TRADE','payout')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('GERENCIAMENTO','take_profit'))
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=='0' or wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=='':
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=100000
   else:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('GERENCIAMENTO','stop_loss')
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=='0' or wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=='':
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=100000
   else:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.getboolean('GERENCIAMENTO','porcentagem')
  except wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMzN:
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\n\n    Inconsistencia nas configuracoes especificadas, \n    voce nao pode deixar campos em branco ou usar virgula em numero decimal!\n    Assista todos os videos de configuracao para nao ter nenhuma duvida!')
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['email'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgM,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['senha'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzg,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['treinamento'].update(disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['real'].update(disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['preco'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['porcentagem_preco'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzM,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['stop_win'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('GERENCIAMENTO','take_profit'),disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['stop_loss'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgz.get('GERENCIAMENTO','stop_loss'),disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['gerenciamento'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQz,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['filtroDbot'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzN,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['martingale'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMz,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['martingalePO'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQMN,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['soros'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNz,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['sorosGale'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQNM,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['nivel_Estrategia'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQM,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['nivel_Estrategia_PO'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzQN,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['fatorMG'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMQ,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz['payout'].update(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzMN,disabled=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('='*27+' COPYRIGHT TOP GAIN '+'='*27)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ=IQ_Option(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgM,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzg)
  wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQzg,wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQzN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.connect()
  if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQzg:
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQNg={"apiKey":"apiKey","authDomain":"dtraders-86997.firebaseapp.com","databaseURL":"https://dtraders-86997.firebaseio.com/","storageBucket":"projectId.appspot.com"}
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQNz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMN(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQNg)
   db=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQNz.database()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMQg()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz['first_name'].upper()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgzQ=db.child("mensagem1").get()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgzN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgzQ.val())
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgNQ=db.child("mensagem2").get()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgNz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgNQ.val())
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzQg=db.child("mensagem3").get()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzQN=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzQg.val())
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzgQ=['demotrade-topgain.firebaseio.com']
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd(target=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzMg).start()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd(target=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzMQ).start()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\n')
   for i in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNzM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgzN):
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN(i,end='')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdzM.flush()
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN(0.05)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQN)
   for u in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNzM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgNz):
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN(u,end='')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdzM.flush()
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN(0.05)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN(' ')
   for l in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgNzM(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzQN):
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN(l,end='')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdzM.flush()
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN(0.05)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN(' ')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzNQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzNg='1'
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNQg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMNg('https://assinantes-dbot.herokuapp.com/assinantes')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNQz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNQg.json()
   for i in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNQz:
    if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzNg==i['email']:
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzNQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
     break
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMzNQ==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\nHA UMA VERSAO MAIS ATUALIZADA, BAIXE NA AREA DE MEMBROS DA HOTMART')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNgQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzgQ(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.get_server_timestamp(),2)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNgz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNgQ.strftime('%d/%m/%Y')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNzQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
   for i in wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNQz:
    if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNgM==i['email']:
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNzQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNzg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdNz(i['data'],'%d/%m/%Y')
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQgz=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNzg+timedelta(days=31))
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNgz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgdNz(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNgz,'%d/%m/%Y')
     dt=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQgz.strftime('%d/%m/%Y')
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQgz-wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNgz
     wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQgM)[:-9]
     if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNgz>wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQgz:
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\nSUA LICENCA VENCEU DIA: {}'.format(dt))
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\nO SISTEMA FUNCIONARA APENAS EM MODO DE TREINAMENTO')
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQzg='PRACTICE'
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQzM='Conta de treinamento'
     else:
      wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\nRESTAM {} DIAS DE SUA LICENCA'.format(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQgM[0:3]))
      if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMg=='r':
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQzg='REAL'
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQzM='Conta real'
      else:
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQzg='PRACTICE'
       wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQzM='Conta de treinamento'
     break
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMNzQ==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\nLICENCA INVALIDA PARA O EMAIL INFORMADO')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\nO SISTEMA FUNCIONARA APENAS EM MODO DE TREINAMENTO')
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQzg='PRACTICE'
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQzM='Conta de treinamento'
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.change_balance(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQzg)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQMg=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzMNQ.get_balance()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\nBANCA INICIAL: ',wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMgQz['currency_char'],wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQMg)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzdM()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQMz.strftime('%d%m%Y')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNM('log de operacoes/'+wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQz+'.txt','w')
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQM.close()
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgMQz==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQM=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ*wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQMg)/100
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgzQ=((wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM*wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQMg)/100)*-1
   else:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgQM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNQ
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgzQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgzNM*-1
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzM==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzNd:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz*wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNQMg)/100
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgzM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
   elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdgQzM==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgzM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNMz
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzNMQ=0
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgz=0
   global wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQgN=0
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMz=db.child("sinais/1").get()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgMQ=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNd(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNgMz.val())
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzgQN=""
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdzQMg=db.child("sinais/1").stream(wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMgQ)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgzMd(target=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNMzQ).start()
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdMzN(5)
   wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMdN('\n'+'-'*48+' ANALISANDO O GRAFICO '+'-'*47+'\n')
  else:
   if wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQzN=="[Errno -2] Name or service not known":
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzQM('    Sem conexao com a internet')
   elif wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdMQzN==wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQNzM:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzQM('    Acho que voce errou seu email ou senha da IQ Option :( por favor verifique e tente novamente')
   else:
    wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdNzQM('    Nao foi possivel se conectar com a IQ Option \n    sua conta nao pode ter autenticacao de 2 fatores ou ter sido criada pelo Facebook.')
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQzgM=wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQgMNz
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcdQgNz.close()
wbvLGSfPmVqtnskABpaTOHxhJuKlyeiXRjrWYUFECDoIcQdNMz()